FROM microsoft/nanoserver AS installer
ARG nodever=10.13.0
ARG arch=x64
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'STOP'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR /downloads
ADD ["https://nodejs.org/dist/v${nodever}/node-v${nodever}-win-${arch}.zip", "./node.zip"]
RUN Expand-Archive node.zip -DestinationPath node;
RUN Remove-Item -Force node.zip


FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-sac2016
USER Administrator
ARG nodever=10.13.0
ARG arch=x64

COPY --from=installer ["C:/downloads/node/node-v${nodever}-win-${arch}", "C:/Program Files/nodejs"]
RUN ["setx", "/M PATH \"$Env:PATH;C:/Program Files/nodejs;C:/Program Files/dotnet;\""]