version: "3.6"

services:
  dotnetbuild:
    image: docker.dev.mfire.co/mindfire.dotnet.node:3.1-sdk-nanoserver
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_sdk
      labels:
        com.mindfiretechnology.description: ".NET SDK build image that includes NodeJS"
  dotnetbuild-2019:
    image: docker.dev.mfire.co/mindfire.dotnet.node:3.1-sdk-nanoserver-2019
    build:
      context: "Windows Server 2019"
      dockerfile: Dockerfile_sdk
      labels:
        com.mindfiretechnology.description: ".NET SDK build image that includes NodeJS"
  dotnetruntime:
    image: docker.dev.mfire.co/mindfire.dotnet.node:3.1-runtime-nanoserver
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_runtime
      labels:
        com.mindfiretechnology.description: ".NET Runtime image that includes NodeJS"
  dotnetruntime-2019:
    image: docker.dev.mfire.co/mindfire.dotnet.node:3.1-runtime-nanoserver-2019
    build:
      context: "Windows Server 2019"
      dockerfile: Dockerfile_runtime
      labels:
        com.mindfiretechnology.description: ".NET Runtime image that includes NodeJS"
  dotnetasp:
    image: docker.dev.mfire.co/mindfire.dotnet.node:3.1-aspnetcore-nanoserver
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_aspnet
      labels:
        com.mindfiretechnology.descripion: "ASP.NET Core Runtime image that includes NodeJS"
  dotnetasp-2019:
    image: docker.dev.mfire.co/mindfire.dotnet.node:3.1-aspnetcore-nanoserver-2019
    build:
      context: "Windows Server 2019"
      dockerfile: Dockerfile_aspnet
      labels:
        com.mindfiretechnology.descripion: "ASP.NET Core Runtime image that includes NodeJS"        