version: "3.6"

services:
  dotnetbuild:
    image: docker.dev.mfire.co/mindfire.dotnet.node:2.2-sdk
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_sdk
      labels:
        com.mindfiretechnology.description: ".NET SDK build image that includes NodeJS"
  dotnetbuildnanoserver:
    image: docker.dev.mfire.co/mindfire.dotnet.node:2.2-sdk-nanoserver
    build:
      context: "Windows Server 2016"
      dockerfile: Dockerfile_sdk
      labels:
        com.mindfiretechnology.description: ".NET SDK build image that includes NodeJS"
  dotnetruntime:
    image: docker.dev.mfire.co/mindfire.dotnet.node:2.2-runtime
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_runtime
      labels:
        com.mindfiretechnology.description: ".NET Runtime image that includes NodeJS"
  dotnetruntimenanoserver:
    image: docker.dev.mfire.co/mindfire.dotnet.node:2.2-runtime-nanoserver
    build:
      context: "Windows Server 2016"
      dockerfile: Dockerfile_runtime
      labels:
        com.mindfiretechnology.description: ".NET Runtime image that includes NodeJS"
  dotnetasp:
    image: docker.dev.mfire.co/mindfire.dotnet.node:2.2-aspnetcore
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_aspnet
      labels:
        com.mindfiretechnology.descripion: "ASP.NET Core Runtime image that includes NodeJS"
  dotnetaspnanoserver:
    image: docker.dev.mfire.co/mindfire.dotnet.node:2.2-aspnetcore-nanoserver
    build:
      context: "Windows Server 2016"
      dockerfile: Dockerfile_aspnet
      labels:
        com.mindfiretechnology.descripion: "ASP.NET Core Runtime image that includes NodeJS"