version: "3.6"

services:
  # Build / SDK
  dotnetbuild:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-sdk
    build:
      context: "Windows Server 2020"
      dockerfile: Dockerfile_sdk
      labels:
        com.mindfiretechnology.description: ".NET SDK build image that includes NodeJS"

  dotnetbuild-win10:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-sdk-win10
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_sdk
      labels:
        com.mindfiretechnology.description: ".NET SDK build image that includes NodeJS"

  dotnetbuild-2019:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-sdk-2019
    build:
      context: "Windows Server 2019"
      dockerfile: Dockerfile_sdk
      labels:
        com.mindfiretechnology.description: ".NET SDK build image that includes NodeJS"  
  
  #Runtime
  dotnetruntime:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-runtime
    build:
      context: "Windows Server 2022"
      dockerfile: Dockerfile_runtime
      labels:
        com.mindfiretechnology.description: ".NET Runtime image that includes NodeJS"
  
  dotnetruntime-win10:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-runtime-win10
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_runtime
      labels:
        com.mindfiretechnology.description: ".NET Runtime image that includes NodeJS"

  dotnetruntime-2019:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-runtime-2019
    build:
      context: "Windows Server 2019"
      dockerfile: Dockerfile_runtime
      labels:
        com.mindfiretechnology.description: ".NET Runtime image that includes NodeJS"

  #ASPNET
  dotnetasp:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-aspnetcore
    build:
      context: "Windows Server 2022"
      dockerfile: Dockerfile_aspnet
      labels:
        com.mindfiretechnology.descripion: "ASP.NET Core Runtime image that includes NodeJS"

  dotnetasp-win10:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-aspnetcore-win10
    build:
      context: "Windows 10"
      dockerfile: Dockerfile_aspnet
      labels:
        com.mindfiretechnology.descripion: "ASP.NET Core Runtime image that includes NodeJS"

  dotnetasp-2019:
    image: docker.dev.mfire.co/mindfire.dotnet.node:6.0-aspnetcore-2019
    build:
      context: "Windows Server 2019"
      dockerfile: Dockerfile_aspnet
      labels:
        com.mindfiretechnology.descripion: "ASP.NET Core Runtime image that includes NodeJS"