FROM mcr.microsoft.com/powershell:nanoserver-1903 AS installer
ARG nodever=10.16.3
ARG arch=x64
SHELL ["pwsh", "-Command"]

WORKDIR /downloads
ADD ["https://nodejs.org/dist/v${nodever}/node-v${nodever}-win-${arch}.zip", "./node.zip"]
RUN Expand-Archive node.zip -DestinationPath node;
RUN Remove-Item -Force node.zip


FROM mcr.microsoft.com/dotnet/core/runtime:2.2-nanoserver-sac2016
ARG nodever=10.16.3
ARG arch=x64

COPY --from=installer ["C:/downloads/node/node-v${nodever}-win-${arch}", "C:/Program Files/nodejs"]
# USER ContainerAdministrator
RUN setx /M PATH "\"${Env:PATH};c:\Program Files\nodejs\";"
# USER ContainerUser